name: democratize_app
description: 民主化運動計画

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  #状態管理
  flutter_riverpod: ^2.4.10
  #セッテイングUI
  settings_ui: ^2.0.2
  #文字流れUI
  marquee: ^2.2.3
  #チャート描画
  fl_chart: ^0.50.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
